### ISSUE TITLE
Registration always respond 500

### ISSUE THREAD

**Issue by Alexfilus** [makeless/makeless-demo#27]
When I try to create user I get 500 response status, but user created successfully, and I can log in.

**Comment by loeffel-io** [comment]
Hey @Alexfilus,

this could belong to two issues: 

This could belong to this [ticket](https://github.com/makeless/makeless-go/issues/10). You should get an 500 status if the user already exists  

**OR**

You did not setup the smtp mailer correctly: https://github.com/makeless/makeless-demo#run-localhost. 
Alternatively you can use the mailgun mailer implementation: https://github.com/makeless/makeless-go-mailer-mailgun

**Comment by loeffel-io** [comment]
Gmail example: 

```
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=587
      - MAILER_IDENTITY=
      - MAILER_USERNAME=lucas.loeffel@gmail.com
      - MAILER_PASSWORD=xxx // gmail app password
```

**Comment by Alexfilus** [comment]
Now gmail not except my creds. But in browser client I logged in successfully. Maybe I need to check some account settings?

**Comment by loeffel-io** [comment]
You have to use an app password: https://support.google.com/mail/answer/185833?hl=en

**Comment by Alexfilus** [comment]
Thanks! Now it works correctly) 
I think email sending should be async, can I send PR for this project?

**Comment by loeffel-io** [comment]
Hey @Alexfilus,

i agree, i will update this soon to the new queue package
You are welcome to send any other pr 

Would love to hear some feedback from you about the demo

**Comment by Alexfilus** [comment]
Mysql is overkill for demo. SQLite3 is simpler but will be enough for local demo purpose. 
I think demo needs examples of different configurations.

**Comment by loeffel-io** [comment]
good point! Will add some examples to the documentation

For now: 
You can just update this line https://github.com/makeless/makeless-demo/blob/master/backend/main.go#L115 by https://gorm.io/docs/connecting_to_the_database.html#SQLite - this should work
